name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        env:
          ACCESS_KEY: ${{ env.ACCESS_KEY }}
        run: |
          echo "ACCESS_KEY=$ACCESS_KEY" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install
